# Generated by Django 5.1.1 on 2024-09-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("book", "0002_book_stock"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="AdminCustomer",
        ),
        migrations.AlterModelTable(
            name="admincustomer",
            table="Admin_user_detail",
        ),
    ]
