# Generated by Django 5.1.1 on 2024-09-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("book", "0002_book_stock"),
        ("user", "0002_rename_customer_admincustomer_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdminCustomer",
            new_name="User",
        ),
        migrations.AlterModelTable(
            name="user",
            table="User_detail",
        ),
    ]
