# Generated by Django 5.1.1 on 2024-09-24 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("book", "0002_book_stock"),
        ("user", "0004_rename_user_user_detail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User_detail",
            new_name="Customer",
        ),
        migrations.AlterModelTable(
            name="customer",
            table="customer_detail",
        ),
    ]
